theme: jekyll-theme-slate

#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Huy

# Short bio or description (displayed in the header)
description: Huy Bik's blog

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/u/5626203?v=4

permalink: /:title/
